# Generated by Django 3.2.19 on 2023-07-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_auto_20230727_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='property',
            name='heating',
        ),
    ]
