# Generated by Django 3.2.19 on 2023-08-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_auto_20230728_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('host', 'Host'), ('renter', 'Renter'), ('anonymous', 'Anonymous')], default='anonymous', max_length=20),
        ),
    ]
