# Generated by Django 3.2.19 on 2023-08-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('host', 'Host'), ('renter', 'Renter'), ('anonymous', 'Anonymous')], default='renter', max_length=20),
        ),
    ]
