# Generated by Django 4.2.4 on 2023-08-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_auto_20230824_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lat',
            field=models.DecimalField(decimal_places=5, max_digits=18),
        ),
        migrations.AlterField(
            model_name='property',
            name='lng',
            field=models.DecimalField(decimal_places=5, max_digits=18),
        ),
    ]
