# Generated by Django 4.2.4 on 2023-08-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_alter_property_lat_alter_property_lng'),
        ('backend_app', '0009_auto_20230828_0911'),
    ]

    operations = [
    ]
